"""Configuration model for lexvault.

Defines the pydantic ``LexVaultConfig`` (the public config contract, validated
at guardrail construction), the dictionary/regex term types, the dictionary
loader, and the placeholder-namespace regex derived from the placeholder format
(used for idempotent re-mask skipping — IMPLICIT_SPEC invariant 16).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict, Field, SecretStr, field_validator

__all__ = [
    "DictionaryTerm",
    "RegexTerm",
    "LexVaultConfig",
    "load_dictionary",
    "placeholder_namespace_regex",
]


class DictionaryTerm(BaseModel):
    """A literal dictionary term to detect and mask."""

    model_config = ConfigDict(extra="ignore")

    term: str
    type: str = "generic"
    case_sensitive: bool = False

    @field_validator("term")
    @classmethod
    def _non_empty(cls, v: str) -> str:
        if not v.strip():
            msg = "dictionary term must be non-empty"
            raise ValueError(msg)
        return v


class RegexTerm(BaseModel):
    """A regex pattern to detect and mask (e.g. internal IDs ``EMP-\\d{4,6}``)."""

    model_config = ConfigDict(extra="ignore")

    name: str
    pattern: str
    type: str = "regex"
    case_sensitive: bool = False

    @field_validator("pattern")
    @classmethod
    def _non_empty(cls, v: str) -> str:
        if not v.strip():
            msg = "regex pattern must be non-empty"
            raise ValueError(msg)
        return v


class LexVaultConfig(BaseModel):
    """Public configuration contract for ``LexVaultGuardrail``.

    These keys are the ``litellm_params`` a user puts in their ``config.yaml``;
    ``extra="allow"`` mirrors LiteLLM's own ``Guardrail`` model
    (``types/guardrails.py:660``) so unknown keys are forwarded harmlessly.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)

    dictionary_path: Path
    org_key: SecretStr
    scope: str = "default"
    fail_open: bool = False
    placeholder_format: str = "[LEX-{code}]"
    vault_path: Path = Field(default_factory=lambda: Path.home() / ".lexvault" / "vault.db")
    mask_system_role: bool = True
    regex_terms: list[RegexTerm] = Field(default_factory=list)

    # Set at construction by the guardrail after load_dictionary(); kept here so
    # the engine/vault have a single config object to read.
    dictionary: list[DictionaryTerm] = Field(default_factory=list, repr=False)

    @field_validator("org_key")
    @classmethod
    def _org_key_non_empty(cls, v: SecretStr) -> SecretStr:
        if not v.get_secret_value():
            msg = "org_key must be non-empty"
            raise ValueError(msg)
        return v

    @field_validator("placeholder_format")
    @classmethod
    def _placeholder_has_code(cls, v: str) -> str:
        if "{code}" not in v:
            msg = "placeholder_format must contain '{code}'"
            raise ValueError(msg)
        return v

    @field_validator("scope")
    @classmethod
    def _scope_non_empty(cls, v: str) -> str:
        if not v.strip():
            msg = "scope must be non-empty"
            raise ValueError(msg)
        return v

    def placeholder_namespace_pattern(self) -> str:
        """Regex matching placeholders generated by this config.

        The ``{code}`` slot in ``placeholder_format`` is replaced by a charset
        class accepting the base32 alphabet (upper A–Z, digits 2–7) plus an
        optional ``-N`` collision disambiguator suffix. Used by the detector
        to pre-exclude placeholder spans (idempotency, invariant 16) and by
        ``unmask`` to find restorable spans (invariant 17).
        """
        return placeholder_namespace_regex(self.placeholder_format)


def placeholder_namespace_regex(placeholder_format: str) -> str:
    r"""Build the namespace regex for a ``[LEX-{code}]``-style format.

    Escapes the literal portions of the format, substitutes a charset for
    ``{code}`` that matches the base32 codes ``derive_placeholder`` emits, and
    appends an optional ``-2``, ``-3`` … collision-suffix group *after* the
    formatted placeholder.

    The suffix must follow the entire formatted placeholder (not the ``{code}``
    slot) because the vault appends it to the already-formatted placeholder
    string (e.g. ``[LEX-ZGJT2O4L]-2``), per ``MappingVault._assign_locked``.
    Putting it inside the ``{code}`` slot would force the regex's closing
    literal (e.g. ``]``) to come after the suffix, which never matches the
    vault's actual emitted form — so a collision-suffixed placeholder could
    neither be pre-excluded by the detector (idempotency, invariant 16) nor
    restored by ``unmask`` (round-trip fidelity, invariant 1).
    """
    # base32[:8] of a 5-byte (40-bit) HMAC digest → up to 8 chars from the
    # base32 RFC4648 alphabet (A-Z, 2-7). Derive uses base32[:8], but be
    # tolerant: accept 1+ base32 chars to also catch short codes / future formats.
    code_charset = r"[A-Z2-7]+"
    # Escape everything, then turn the escaped "{code}" back into the charset.
    escaped = re.escape(placeholder_format)
    escaped_code = re.escape("{code}")
    body = escaped.replace(escaped_code, code_charset)
    # Collision disambiguator is appended to the WHOLE formatted placeholder
    # by the vault (outside any closing bracket), so match it here at the end.
    return body + r"(?:-\d+)?"


def load_dictionary(path: Path | str) -> tuple[list[DictionaryTerm], list[RegexTerm]]:
    r"""Load dictionary + regex terms from a YAML or JSON file.

    Accepted shapes::

        terms:
          - term: Project Titan
            type: codename
        regex_terms:
          - name: Employee ID
            pattern: 'EMP-\d{4,6}'

    JSON files use the same key names. An empty dictionary is allowed (the
    guardrail becomes a no-op detector) but a missing file is an error.
    """
    p = Path(path)
    if not p.exists():
        msg = f"dictionary file not found: {p}"
        raise FileNotFoundError(msg)

    raw: dict[str, Any]
    if p.suffix.lower() in {".yaml", ".yml"}:
        raw = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    elif p.suffix.lower() == ".json":
        import json

        raw = json.loads(p.read_text(encoding="utf-8"))
    else:
        # Default to YAML (yaml is a superset of JSON and the documented format).
        raw = yaml.safe_load(p.read_text(encoding="utf-8")) or {}

    if not isinstance(raw, dict):
        msg = f"dictionary file must be a mapping at top level, got {type(raw).__name__}"
        raise ValueError(msg)

    terms = [DictionaryTerm(**t) for t in raw.get("terms", [])]
    regex_terms = [RegexTerm(**r) for r in raw.get("regex_terms", [])]
    return terms, regex_terms
